### ISSUE TITLE
 git-init error

### ISSUE THREAD

**Issue by omerffd** [ucoruh/ce103-algorithms-and-programming-I#15]
After typing git init into git bash, it gives an error. I don't understand why git init gives such an error. Can you explain this issue for me? The error is this :
 git init
error: chmod on /mnt/c/Users/Asus/Desktop/sample/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.repositoryformatversion' to '0'

**Comment by windowz414** [comment]
> error: chmod on /mnt/c/Users/Asus/Desktop/sample/.git/config.lock failed: Operation not permitted

This one looks rather like permission modification failure. WSL bind mounts Windows partitions and bind mounts that aren't EXT4 (Windows uses NTFS) are unallowed to have custom permission mods. Git, from what I know, tried to change permission mods of its folder, `.git` to unallow possible tampering with the repositories. Initialize the repository either in Windows itself or don't try to use Git on Windows path in WSL.

**Comment by ucoruh** [comment]
## Problem
Simply, if you have a git client, that means the git-bash console opened on Windows OS, and at the same time, if you have tried to modify the .git folder with another git such as WSL installed git instance. Git will detect the lock file and won't permit this operation. 
## Solution
I recommend closing all clients in Windows OS. If you can't solve the issue, just restart the PC and open WSL again. 
In your setup, 
## How it works
Windows and WSL have git clients, but they are different applications. They detect that a client uses a git repo with this .lock files.

**Comment by ucoruh** [comment]
> > error: chmod on /mnt/c/Users/Asus/Desktop/sample/.git/config.lock failed: Operation not permitted
> 
> This one looks rather like permission modification failure. WSL bind mounts Windows partitions and bind mounts that aren't EXT4 (Windows uses NTFS) are unallowed to have custom permission mods. Git, from what I know, tried to change permission mods of its folder, `.git` to unallow possible tampering with the repositories. Initialize the repository either in Windows itself or don't try to use Git on Windows path in WSL.

Think simple. This is an issue in StackOverflow but let's start from the basics.
