### ISSUE TITLE
it's about week5-page 499

### ISSUE THREAD

**Issue by elifKALENDER** [ucoruh/ce103-algorithms-and-programming-I#17]
I can't understand that line. I've already searched few sites but I couldn't find clear explanation. 
 The code is `scanf("%[^\n]%*c", s1.name)`. 
-For instance , what is `[^\n]` mean.
-In addition ,what is `%*c` mean. Why we use asterisk `*` in `%*c`.

**Comment by windowz414** [comment]
@elifKALENDER this was answered in a StackOverflow post.

https://stackoverflow.com/questions/30065675/what-does-scanf-nc-mean

**Comment by ucoruh** [comment]
- It reads the entire line with whitespaces until it found a newline character \n. In normal if there is a whitespace then processing finishes for scanf. 
- Each character sets a flag in the scanf function. There is a simple implementation for scanf; maybe you can check the function code. 
https://opensource.apple.com/source/xnu/xnu-792/libkern/stdio/scanf.c.auto.html
