### ISSUE TITLE
About an error called unrelated histories

### ISSUE THREAD

**Issue by elifKALENDER** [ucoruh/ce103-algorithms-and-programming-I#18]
When I create a local repo, master branch is occurred automatically. After
that, I follow these steps respectively.

> 1,2,3,4,5,6 steps on [Computer Engineering-Notebook&amp;Project: GiT Notes&#10024;🌠](https://eeliphu.blogspot.com/2023/03/git-notes.html) and;

> 7- `git branch -M main` (your computer create main branch called master, you can change this name with
> this code)

> 8-`git remote origin <remote repo address>`(if
> called an error about "subcommand”, you use; `git remote add origin <address origin>` )

> 9- `git push origin main` (might call a non-fast-forward error)

> 10-To solve non-fast-forward error; `git pull origin main`(main branch name) or `git fetch origin` (It is the point, you
> have to do pull and fetch before push!!!)

> 11- After that, called an error about unrelated histories (because you
> change your main branch name as main to master) `git pull origin main --allow-unrelated-histories`

> 12- `git pull origin main`

> 13-`git push origin main`

I am not sure if it is decent approach or not. What can I change to fix this process?(Also ,I use Git Extentions)

**Comment by ucoruh** [comment]
I recommend you follow my notes, after the git setup, if your git creates master always you need to config it defaults 

`> git config --global init.defaultBranch main`

https://ucoruh.github.io/ce103-algorithms-and-programming-I/week-3-git/ce103-week-3-git/#installation-of-git-extension-windows-1

There is nothing to fix, you should add a remote repository and then you should check it.  command-8 has a problem there should be `add`  (`git remote add origin <github link>`) so without adding a remote repository you are trying to pull from the remote repository that has not been added. 
After adding use `git remote -v` to see if added or not then you can use normal commands.

**Comment by elifKALENDER** [comment]
The problem have solved successfully.
I use these steps,

1-`> git config --global init.defaultBranch main`

2-`git remote add origin <github link>`

3-`git push -u origin <branch>`

Now, I do not take any error during git push process. As well, my  main branch is created as main automatically. So, I do not have to arrange manually. I avoid that unrelated histories error with command-3.

Also, I rearrange my git notes: [https://eeliphu.blogspot.com/2023/03/git-notes.html](https://eeliphu.blogspot.com/2023/03/git-notes.html)

Thank you...
